version: '3'

services: 

  auth_db:
    container_name: auth-db
    image: mongo

    volumes:
      - ./data:/data/db

  auth_server:
    build: .

    command: python3 -m flask --app auth_server run --host=0.0.0.0

    volumes:
      - ./auth_server:/usr/src/app

    ports: 
      - 5000:5000

    depends_on:
      - auth_db