version: '3'

services: 

  auth_db:
    image: mongo

    hostname: auth-db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

    volumes:
      - ./data:/data/db

  auth_server:
    build: .

    command: python3 -m flask --app auth_server run --host=0.0.0.0

    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=password

    volumes:
      - ./auth_server:/usr/src/app

    ports: 
      - 5000:5000

    depends_on:
      - auth_db