
name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker compose build

    - name: Run Unit Tests
      run: docker compose run auth_server python3 -m pytest

    - name: Make Test Request
      run: |
        docker compose up -d
        sleep 5
        curl -X POST localhost:5000/auth/get-public-key
        docker compose down
    

  